### ISSUE TITLE
keep field summary in auto doc pydantic

### ISSUE THREAD

**Issue by tylerflex** [flexcompute-readthedocs/tidy3d-docs#114]
Inherited properties dont show up, let's add them back yea?
https://github.com/flexcompute-readthedocs/tidy3d-docs/commit/68d31b55da72ae5dd4b7d25a86913afa31e290cd

**Comment by momchil-flex** [comment]
Maybe worth playing around with the possible settings one more time... Initially this was removed because the documents were very verbose with some attributes repeated in multiple sections. It seems like each section works in a different way though and it's hard to remove any of them without losing something. I wonder if it's possible, instead of returning the "field summary", to make sure that inherited properties show up in the current setup.

**Comment by tylerflex** [comment]
Seems this might not be possible, see https://github.com/mansenfranzen/autodoc_pydantic/issues/32. I can't seem to implement this in the api.rst as it stands now.

**Comment by tylerflex** [comment]
Also this: https://autodoc-pydantic.readthedocs.io/en/v1.4.0/faq.html#show-inherited-fields-validators

**Comment by momchil-flex** [comment]
I'm a bit confused, don't these links exactly provide a way to do what we want?

sphinx is still abstruse to me though, so it's hard to translate the example exactly. But what happens if we try e.g. 

```
Simulation
----------

.. autosummary::
   :toctree: _autosummary/
   :inherited-members: Tidy3dBaseModel

   Simulation
```

in `api.rst`? Unfortunately I'm getting some pesky errors when trying to compile the docs locally so I couldn't try.

**Comment by momchil-flex** [comment]
I guess for `Simulation` this wouldn't matter, but it would for other things like sources, monitors, and data structures.

**Comment by tylerflex** [comment]
I get 
```
/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/api.rst:229: ERROR: Error in "autosummary" directive:
unknown option: "inherited-members".
```

I also tried
```
.. autosummary::
   :toctree: _autosummary/

   Simulation
      :inherited-members: Tidy3dBaseModel
```
but nothing showed up.

**Comment by momchil-flex** [comment]
Sorry, I think nothing is supposed to show up for Simulation, because the members shown *stop* at Tidy3dBaseModel members. Simulation was a bad example, could you try with something that's missing some inherited members, like PlaneWave?

**Comment by tylerflex** [comment]
Tidy3dBaseModel adds methods like `updated_copy` that didn't show up though. Also, the first thing gave an error because inherited members was not a recognized option. I think it might be because we're working with an old version of sphinx.

**Comment by momchil-flex** [comment]
I guess I'm being unclear again. If you look at the example, `:inherited-members: Tidy3dBaseModel` will *not* add members of `Tidy3dBaseModel`, only of classes up to that one. Which should have no effect for Simulation.

**Comment by momchil-flex** [comment]
(I am not sure if `BaseModel` should then be directly imported in tidy3d though, as opposed to being used as pd.BaseModel)
