### ISSUE TITLE
Script to update links in docs

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute-readthedocs/tidy3d-docs#118]
Ideally, we shouldn't have to manually edit the links in the docs to point to the latest pre-release version. Would be nice to have an automated way to update from one version to another.

It seems to me that the version should be just taken from `tidy3d/version.py`. At what level can we automate this?

**Comment by tylerflex** [comment]
I think I found a solution to this @momchil-flex / @tomflexcompute .
Basically we can use **relative** links in the notebooks. For example.

```
https://docs.flexcompute.com/projects/tidy3d/en/v1.9.0rc2/_autosummary/tidy3d.plugins.adjoint.run.html
```
becomes
```
../_autosummary/tidy3d.plugins.adjoint.run.html
```
when used in a notebook (the `../` is because the source is in the following structure
```
html/
    notebooks/
       GratingCoupler.ipynb
       ...
   _autosummary/
   ...
```
so I think replacing `https://docs.flexcompute.com/projects/tidy3d/en/v1.9.0rc2/` with `../` in all of the notebooks should mean we dont need to worry about the branch / tag name anymore. Will try it now

**Comment by tylerflex** [comment]
corresponding PR
https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/125
